spring.application.name=Auth-Service

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# JWT defaults (override in environment)
jwt.secret= zr4K7SV93VSpBfMgCiTLJ2BuYevwadH5ykZktMpfosh
jwt.expiration=3600000

# Datasource (configure as needed)
spring.datasource.url=jdbc:mysql://localhost:3306/authdb
spring.datasource.username=root
spring.datasource.password=root
